language: groovy
sudo: false
cache:
  directories:
  - "$HOME/.gradle/caches"
  - "$HOME/.gradle/wrapper"
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
jdk:
- oraclejdk8
install: true
script: "./travis-build.sh"
env:
  global:
  - secure: IcaIl4ovzdqrrqAZj2o1xj7gwpioJdxewM13LRv0z88xLCOxeUeyIL++vepcuqYbxGZNTsEjtzsJrUwO3UkZpYgSaQagqvtFG1n5/rnIo3kTXypsjK9agrAvenI+cmry5lwm8DcPirKape3ndXRDbpViOgdl4kjfGOiqqaIQzms=
  - secure: JbkNywQe0C6NILsbPvmugM93kjxWnJ+bAm1UVKa+buqKmYdfIUXy5mgjkNp+z+8Q9by+79T+hsvtPyIccM+KCl09lJGr6x6wWfpRIIyVqytMvHhcdYpCAE3+uIHmzIZyWzsvjBpw3JAtSu9dI42DSDCVjrSyWpClB3JEpniLz2g=
  - secure: 20i/GdaObR4E85CeGkfR1Gwgp5j9Ad3sR64jlem99nXLT2bQQtt+5+H6Z/tEE8zc48K84aPg3+JNJnPN0lEmXtvIETEfe4xz0k+Y9+b7W126HnUgvgjNlLO70UTLpBkgovNaePHEBKM4KtoWTrSlOn31Fn2+9bSLgvxWf7EwjyY=
  - secure: aVzGU8h0AjBGkr/6iosWLQECnxpqQ197DKWOAyBwY2+qX92W8F0opGsQCQjJ3vVtotV/J5XQkQ/Smm/fBQNs1zBaZtlkXloKo1pe2/c87LD5Oqu4ZY/otrT6K46KB0TY6XLJgbdKsal+yt5+5WkcoD73ksb7lQiKu0Qovd9u7gg=
  - secure: foqsoPY9e7Y81qVvCPHupLllYXbNwc3WHVUQxqfDK0PCebJ3+GTZsA5D5034wD6rInsGlgktcXQ5V3BlEfXOagNz7ZanzSKoCSFJVCPX9NWaNeCF7KXmsZ/F0hbDf+rQ6HOcpxFGb3TWZ3RPI6QRelJVwV0cB0lwqHSkeD8m0BM=
